spring:
  application:
    name: eureka-server

---
spring:
  profiles: s2
server:  # 服务端口
  port: 8762
eureka:
  instance:
    hostname: eureka-server2
  client:
    service-url:   #  eureka server 的地址， 咱们单实例模式就写自己好了
      defaultZone:  http://eureka-server1:8761/eureka,http://eureka-server3:8763/eureka
    register-with-eureka: false  # 不向eureka server 注册自己
    fetch-registry: false  # 不向eureka server 获取服务列表
---
spring:
  profiles: s3
server:  # 服务端口
  port: 8763
eureka:
  instance:
    hostname: eureka-server3
  client:
    service-url:   #  eureka server 的地址， 咱们单实例模式就写自己好了
      defaultZone:  http://eureka-server1:8761/eureka,http://eureka-server2:8762/eureka
    register-with-eureka: false  # 不向eureka server 注册自己
    fetch-registry: false  # 不向eureka server 获取服务列表